---
- name: 'install yard gem'
  shell: >
      /opt/puppetlabs/puppet/bin/gem install yard
  when: puppet_repositories_version == 4

- name: 'install puppetlabs-strings'
  shell: >
      /opt/puppetlabs/puppet/bin/gem install puppet-strings
  when: puppet_repositories_version == 4

- name: "install git"
  yum:
    name: 'git'
    state: 'present'

- name: "install module PR into installer directory"
  shell: >
      cd {{ (item.split("/")[0] == 'theforeman') | ternary("/usr/share/foreman-installer/modules", "/usr/share/katello-installer-base/modules") }} &&
      rm -rf {{ item.split("/")[1] }} &&
      git clone https://github.com/{{ item.split("/")[0] }}/puppet-{{ item.split("/")[1] }} {{ item.split("/")[1] }} &&
      cd {{ item.split("/")[1] }} &&
      git fetch origin pull/{{ item.split("/")[2] }}/head:pr &&
      git merge pr
  with_items: "{{ foreman_installer_module_prs.split(',') }}"
