---
- name: 'Update packages'
  yum:
    name: '*'
    update_cache: yes
    state: latest

- name: 'Install foreman-installer'
  yum:
    name: foreman-installer
    state: latest

- name: 'Install additional packages'
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ foreman_installer_additional_packages }}"
