---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: pulp-resource-manager
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: pulp-resource-manager
spec:
  template:
    metadata:
      labels:
        app: foreman
        service: pulp-resource-manager
    spec:
      containers:
        - name: pulp-resource-manager
          securityContext: {}
          state: present
          image: "{{ registry }}/pulp-resource-manager:latest"
      serviceAccount: "{{ project_name }}-anyuid"
      serviceAccountName: "{{ project_name }}-anyuid"
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
