---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: pulp-streamer
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: pulp-streamer
spec:
  template:
    metadata:
      labels:
        app: foreman
        service: pulp-streamer
    spec:
      containers:
        - name: pulp-streamer
          securityContext: {}
          state: present
          ports:
            - protocol: TCP
              containerPort: 8751
          image: "{{ registry }}/pulp-streamer:latest"
      serviceAccount: anyuid
      serviceAccountName: anyuid
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
