---
apiVersion: v1
kind: Service
metadata:
  name: pulp
  namespace: "{{ project_name }}"
  labels:
    app: pulp
spec:
  selector:
    app: pulp
  ports:
    - protocol: TCP
      targetPort: 443
      name: port-443-tcp
      port: 443
