---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: pulp-worker
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: pulp-worker
spec:
  template:
    metadata:
      labels:
        app: foreman
        service: pulp-worker
    spec:
      serviceAccount: anyuid
      serviceAccountName: anyuid
      containers:
        - name: pulp-worker
          securityContext: {}
          state: present
          volumeMounts:
            - readOnly: false
              mountPath: /var/lib/pulp
              name: pulp-data
            - readOnly: false
              mountPath: /etc/puppet
              name: puppet-data
          image: "{{ registry }}/pulp-worker:latest"
      volumes:
        - name: pulp-data
          persistentVolumeClaim:
            claimName: pulp-data
        - name: puppet-data
          persistentVolumeClaim:
            claimName: puppet-data
  replicas: "{{ pulp_worker_count }}"
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
