---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: squid
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: squid
spec:
  template:
    metadata:
      labels:
        app: foreman
        service: squid
    spec:
      containers:
        - name: squid
          securityContext: {}
          state: present
          ports:
            - protocol: TCP
              containerPort: 3128
          image: "{{ registry }}/squid:latest"
      serviceAccount: anyuid
      serviceAccountName: anyuid
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
