---
project_dir: "{{ lookup('pipe', 'pwd') }}/../"
working_dir: "{{ project_dir }}"
certificates_ca_directory: "{{ working_dir }}/certs"
build_dir: "{{ working_dir }}/certs"
registry: oc-cluster
openshift_data_dir: /home/origin
services: ''
bin_dir: ~/bin
