---
- name: 'Ensure libselinux-python is installed'
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - libselinux-python
    - libsemanage-python
  tags:
    - env_setup
  when: ansible_os_family == 'RedHat'

- name: 'Set selinux state'
  selinux:
    policy: targeted
    state: "{{ selinux_state }}"
  tags:
    - env_setup
  when: ansible_os_family == 'RedHat'
