---
- name: 'Ensure libselinux-python is installed'
  yum:
    name: 'libselinux-python'
    state: installed
  tags:
    - env_setup
  when: ansible_os_family == 'RedHat'

- name: 'Set selinux state'
  selinux:
    policy: targeted
    state: "{{ selinux_state }}"
  tags:
    - env_setup
  when: ansible_os_family == 'RedHat'
