sudo: false
language: python
python:
  - 2.7
install:
  - pip install ansible-lint
  - rvm install 2.2.4
script:
  - bundle install
  - bundle exec rake
  - ansible-lint -r rules/ playbooks/*
  - ansible-lint -r rules/ roles/*
  - ansible-lint -r rules/ containers/roles/*
