---
- name: 'Check if foreman_installer_options is a string'
  fail:
    msg: 'foreman_installer_options must be an array'
  when: foreman_installer_options is string

- name: 'Read installer version'
  slurp:
    src: /usr/share/foreman-installer/VERSION
  register: foreman_installer_version_file

- debug:
    msg: "Foreman installer version {{ foreman_installer_version_file['content'] | b64decode }}"

- name: 'Join options'
  set_fact:
    foreman_installer_options_joined: "{{ foreman_installer_options | join(' ') }} {{ foreman_installer_options_internal_use_only | join(' ') }}"

- name: 'Replace certs-tar-file with legacy option'
  set_fact:
    foreman_installer_options_joined: "{{ foreman_installer_options_joined | replace('--certs-tar-file', '--foreman-proxy-content-certs-tar') }}"
  when: foreman_installer_version_file['content'] | b64decode is version('1.21', '<')

- name: 'Run installer'
  shell: >
      {{ foreman_installer_command }} {{ (foreman_installer_verbose == True) | ternary("-v", "") }}
      {{ foreman_installer_scenario_flag }} {{ foreman_installer_scenario }}
      {{ foreman_installer_options_joined }}
  when: not foreman_installer_skip_installer
  tags:
    - installation
