---
- include: packages.yml

- include: locales.yml
  when: ansible_os_family == 'Debian'

- include: module_pr.yml
  when: foreman_installer_module_prs != ""

- include: install.yml
  when: foreman_installer_upgrade == False

- include: upgrade.yml
  when: foreman_installer_upgrade == True
