---
- name: "Determine if Puppet 4 is used"
  stat:
    path: /opt/puppetlabs/puppet/bin/gem
  register: puppetlabs_gem

- name: "Install gems to rebuild the kafo module cache"
  gem:
    name: "{{ item }}"
    executable: /opt/puppetlabs/puppet/bin/gem
  with_items:
    - yard
    - puppet-strings
  when: puppetlabs_gem.stat.exists
  tags:
    - packages

- name: "install git"
  package:
    name: 'git'
    state: 'present'

- name: "install module PR into installer directory"
  shell: >
      cd {{ (item.split("/")[0] == 'theforeman') | ternary("/usr/share/foreman-installer/modules", "/usr/share/katello-installer-base/modules") }} &&
      rm -rf {{ item.split("/")[1] }} &&
      git clone https://github.com/{{ item.split("/")[0] }}/puppet-{{ item.split("/")[1] }} {{ item.split("/")[1] }} &&
      cd {{ item.split("/")[1] }} &&
      git fetch origin pull/{{ item.split("/")[2] }}/head:pr &&
      git merge pr
  with_items: "{{ foreman_installer_module_prs.split(',') }}"
  tags:
    - packages
