---
- name: 'Install foreman-installer'
  package:
    name: foreman-installer
    state: latest
  tags:
    - packages

- name: 'Install additional packages'
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ foreman_installer_additional_packages }}"
  tags:
    - packages
