---
- name: 'Update foreman-release-scl'
  yum:
    name: foreman-release-scl
    update_cache: yes
    state: latest

- name: 'Stop katello-services'
  command: katello-service stop

- name: 'Update packages'
  yum:
    name: '*'
    update_cache: yes
    state: latest

- name: 'Check if foreman_installer_options is a string'
  fail:
    msg: 'foreman_installer_options must be an array'
  when: foreman_installer_options is string

- name: 'Run installer upgrade'
  command: >
    {{ foreman_installer_command }} {{ (foreman_installer_verbose == True) | ternary("-v", "") }}
    --disable-system-checks
    --upgrade
    {{ foreman_installer_scenario_flag }} {{ foreman_installer_scenario }}
    --certs-update-all
    {{ foreman_installer_options | join(" ") }}
    {{ foreman_installer_options_internal_use_only | join(" ") }}
  when: not foreman_installer_skip_installer
