---
- name: 'Stop katello-services'
  command: katello-service stop

- name: 'Update packages'
  import_role:
    name: update_os_packages

- name: 'Run installer upgrade'
  import_tasks: "install.yml"
  vars:
    foreman_installer_options_internal_use_only: "{{ [ '--disable-system-checks', '--upgrade', '--certs-update-all' ] + foreman_installer_options_internal_use_only }}"
