---
- name: 'Destroy boxes'
  command: "vagrant destroy {{ forklift_boxes.keys()|join(' ') }}"
  args:
    chdir: "{{ current_directory }}"

- name: 'Remove box file'
  file:
    path: "{{ current_directory }}/.tmp_boxes/{{ forklift_name }}.yaml"
    state: "absent"
