---
- set_fact:
    current_directory: "{{ lookup('pipe','dirname `pwd`') }}"

- name: 'Check variables defined'
  fail:
    msg: 'Please define forklift_name which determines the file boxes are deployed to'
  when: forklift_name is undefined

- name: 'Check Forklift state'
  fail:
    msg: 'The forklift_state variable is undefined. Please use pass "-e "forklift_state=up"" to spin up the boxes or "-e "forklift_state=destroy"" to destroy the boxes'
  when: forklift_state is undefined

- name: 'Bring boxes up'
  include: 'up.yml'
  when: forklift_state == 'up'

- name: 'Destroy boxes'
  include: 'destroy.yml'
  when: forklift_state == 'destroy'

- name: 'Refresh inventory'
  meta: refresh_inventory
