---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: memcached
  namespace: "{{ project_name }}"
  labels:
    app: memcached
spec:
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: manageiq/memcached
          ports:
            - containerPort: 11211
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            tcpSocket:
              port: 11211
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            tcpSocket:
              port: 11211
          env:
            - name: MEMCACHED_MAX_MEMORY
              value: "64"
            - name: MEMCACHED_MAX_CONNECTIONS
              value: "1024"
            - name: MEMCACHED_SLAB_PAGE_SIZE
              value: "1m"
