---
- hosts: localhost
  vars:
    certificates_services:
      - name: pulp
        common_name: pulp
      - name: pulp-client
        common_name: admin
      - name: server
        common_name: "{{ lookup('ENV', 'APPLICATION_HOSTNAME') }}"
  roles:
    - certificates
    - client-rpm

- hosts: localhost
  gather_facts: no
  vars:
    working_dir: /root
    certificates_ca_directory: "{{ working_dir }}/certificates"
  tasks:
    - slurp:
        src: "{{ certificates_ca_directory + '/certs/' + item }}"
      register: cert_files
      with_items:
        - ca.crt
        - pulp.crt
        - pulp-client.crt
        - server.crt

    - name:
      set_fact:
        certs: "{{ certs|default({}) | combine({item.item.replace('.', '_').replace('-', '_'): item.content | b64decode}) }}"
      with_items:
        - "{{ cert_files.results }}"

    - slurp:
        src: "{{ certificates_ca_directory + '/private/' + item }}"
      register: key_files
      with_items:
        - ca.key
        - pulp.key
        - pulp-client.key
        - server.key

    - name:
      set_fact:
        keys: "{{ keys|default({}) | combine({item.item.replace('.', '_').replace('-', '_'): item.content | b64decode}) }}"
      with_items:
        - "{{ key_files.results }}"

    - name: 'Write secrets to file'
      copy:
        content: "{{ certs | combine(keys) | to_nice_yaml }}"
        dest: "{{ working_dir }}/secrets.yml"
