---
- name: Scale Qpid pods to 0
  openshift_raw:
      name: qpid
      namespace: "{{ project_name }}"
      replicas: 0
  tags:
    - stop
    - restart

- name: Create Qpid deployment
  openshift_raw:
      state: "{{ deployment_state }}"
      force: false
      definition:
          apiVersion: v1
          kind: DeploymentConfig
          metadata:
              name: qpid
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: qpid
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: qpid
                  spec:
                      containers:
                        - name: qpid
                          securityContext: {}
                          state: present
                          image: "{{ registry }}/qpid:latest"
                      serviceAccount: anyuid
                      serviceAccountName: anyuid
              replicas: 1
              strategy:
                  type: Rolling
                  rollingParams:
                      timeoutSeconds: 900
  tags:
    - start
    - restart
    - destroy
