---
- name: 'install vagrant-libvirt requirements'
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt-devel
    - ruby-devel
    - gcc

- name: 'install vagrant-libvirt'
  command: vagrant plugin install vagrant-libvirt
