---
- name: 'Log httpd to stdout'
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ErrorLog'
    line: 'ErrorLog /dev/stderr'

- name: 'Symlink published Pulp data to /var/www/pub'
  file:
    state: link
    src: /var/lib/pulp/published
    dest: /var/www/pub

- name: 'Allow access to content wsgi'
  blockinfile:
    path: /etc/httpd/conf.d/pulp_content.conf
    block: |
      <Directory /usr/share/pulp/wsgi>
        Require all granted
      </Directory>

- name: 'Remove Pulp API server config from httpd'
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/httpd/conf.d/pulp.conf
    - /etc/httpd/conf.d/pulp_puppet.conf
