---
- name: "Login as admin"
  command: oc login -u system:admin
  when: minishift or cluster_up

- name: "{{ project_name }}-anyuid service account"
  k8s_raw:
    state: present
    force: false
    resource_definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ project_name }}-anyuid"
        namespace: "{{ project_name }}"

- name: Add anyuid scc to anyuid service account
  command: oc adm policy add-scc-to-user anyuid system:serviceaccount:{{ project_name }}:{{project_name }}-anyuid
  when: minishift or cluster_up

- name: Role for secret read
  k8s:
    state: present
    resource_definition:
      kind: ClusterRole
      apiVersion: v1
      metadata:
        name: "{{ project_name }}-secret-reader"
        namespace: "{{ project_name }}"
      rules:
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["get", "list"]

- name: Role for secret edit
  k8s:
    state: present
    resource_definition:
      kind: ClusterRole
      apiVersion: v1
      metadata:
        name: "{{ project_name }}-secret-editor"
        namespace: "{{ project_name }}"
      rules:
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["create", "patch"]

- name: Bind secret-reader to "{{ project_name }}-anyuid"
  k8s_raw:
    state: present
    resource_definition:
      apiVersion: v1
      kind: RoleBinding
      metadata:
        name: "{{ project_name }}-secret-reader-binding"
        namespace: "{{ project_name }}"
      roleRef:
        kind: ClusterRole
        name: "{{ project_name }}-secret-reader"
      subjects:
        - kind: ServiceAccount
          name: "{{ project_name }}-anyuid"
          namespace: "{{ project_name }}"

- name: Bind secret-editor to "{{ project_name }}-anyuid"
  k8s_raw:
    state: present
    resource_definition:
      apiVersion: v1
      kind: RoleBinding
      metadata:
        name: secret-editor-binding
        namespace: "{{ project_name }}"
      roleRef:
        kind: ClusterRole
        name: "{{ project_name }}-secret-editor"
      subjects:
        - kind: ServiceAccount
          name: "{{ project_name }}-anyuid"
          namespace: "{{ project_name }}"

- name: "Login as admin"
  command: oc login -u developer -p a
  when: minishift or cluster_up
