---
- name: Login as system admin
  command: oc login -u system:admin
  when: minishift or cluster_up

- name: Add anyuid scc to anyuid service account
  command: oc adm policy add-scc-to-user anyuid system:serviceaccount:{{ project_name }}:anyuid

- name: Login as developer
  command: oc login -u developer -p a
  when: minishift or cluster_up

- name: anyuid service account
  k8s:
    state: present
    force: false
    resource_definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: anyuid
        namespace: "{{ project_name }}"

- name: Allow anyuid service account to create secrets
  k8s:
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: anyuid-edit
        namespace: "{{ project_name }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
      - kind: ServiceAccount
        name: anyuid
        namespace: "{{ project_name }}"
