---
- include_tasks: release_repos.yml
  when: katello_repositories_use_release and not katello_repositories_use_koji

- include_tasks: koji_repos.yml
  when: katello_repositories_use_koji

  # Required for el6 clients
- include_tasks: qpid.yml
  when: ansible_distribution_major_version == "6"
