---
- name: 'Remove katello-repos'
  yum:
    name: katello-repos
    state: absent

- name: 'Katello Koji repository'
  yum_repository:
    name: katello-koji
    description: "Katello {{ katello_repositories_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/katello-{{ katello_repositories_version }}/katello/el{{ ansible_distribution_major_version }}/x86_64/"
    priority: 1
    gpgcheck: 0

- name: 'Katello Client Koji repository'
  yum_repository:
    name: katello-client-koji
    description: "Katello {{ katello_repositories_version }} Client Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/katello-{{ katello_repositories_version }}/client/el{{ ansible_distribution_major_version }}/x86_64/"
    priority: 1
    gpgcheck: 0

- name: 'Candlepin Koji repository'
  yum_repository:
    name: candlepin-koji
    description: "Candlepin {{ katello_repositories_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/katello-{{ katello_repositories_version }}/candlepin/el{{ ansible_distribution_major_version }}/x86_64/"
    priority: 1
    gpgcheck: 0

- name: 'Pulp Koji repository'
  yum_repository:
    name: pulp-koji
    description: "Pulp {{ katello_repositories_version }} Koji Repository"
    baseurl: "https://repos.fedorapeople.org/repos/pulp/pulp/{{ katello_repositories_pulp_release }}/{{ katello_repositories_pulp_version }}/{{ ansible_distribution_major_version }}Server/x86_64/"
    priority: 1
    gpgcheck: 0

- name: 'Katello Client Koji repository'
  yum_repository:
    name: katello-client-koji
    description: "Katello {{ katello_repositories_version }} Client Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/katello-{{ katello_repositories_version }}/client/el{{ ansible_distribution_major_version }}/x86_64/"
    priority: 1
    gpgcheck: 0
