- name: Manage the lifecycle of Foreman on OpenShift™
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    minishift: true
    cluster_up: false
    pulp_worker_count: 2
    registry: quay.io/foreman
    deployment_state: present
    project: foreman
    enabled_services:
      - memcached
      - postgres
      - puppet
      - pulp
      - candlepin
  pre_tasks:
    - set_fact:
        project_name: "{{ project | lower }}"

    - set_fact:
        application_hostname: "{{ application_hostname | default('') }}"
    - shell: minishift ip
      register: minishift_ip
      when: minishift == true
    - set_fact:
        application_hostname: "{{ project_name }}.{{ minishift_ip.stdout }}.nip.io"
      when: application_hostname == '' and minishift == true and cluster_up == false
    - set_fact:
        application_hostname: "{{ project_name }}.{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.nip.io"
      when: application_hostname == '' and cluster_up == true and minishift == false
  roles:
    - project
    - service-accounts
    - foreman
    - foreman-proxy
