- name: Manage the lifecycle of Foreman on OpenShift™
  hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - role: ansible-kubernetes-modules
  vars_files:
    - secrets.yml
  vars:
    pulp_worker_count: 2
    registry: projgriffin
  tasks:
    - import_tasks: deploy/project.yml

    - import_tasks: deploy/secrets/secrets.yml

    - import_tasks: deploy/service_accounts.yml

    - import_tasks: deploy/postgres/persistent_volume_claims.yml
    - import_tasks: deploy/pulp/persistent_volume_claims.yml

    - import_tasks: deploy/candlepin/services.yml
    - import_tasks: deploy/foreman-proxy/services.yml
    - import_tasks: deploy/foreman/services.yml
    - import_tasks: deploy/postgres/services.yml
    - import_tasks: deploy/pulp/services.yml
    - import_tasks: deploy/puppet/services.yml
    - import_tasks: deploy/qpid/services.yml

    - import_tasks: deploy/candlepin/deployments.yml
    - import_tasks: deploy/foreman-proxy/deployments.yml
    - import_tasks: deploy/foreman/deployments.yml
    - import_tasks: deploy/postgres/deployments.yml
    - import_tasks: deploy/pulp/deployments.yml
    - import_tasks: deploy/puppet/deployments.yml
    - import_tasks: deploy/qpid/deployments.yml

    - import_tasks: deploy/candlepin/routes.yml
    - import_tasks: deploy/foreman/routes.yml
    - import_tasks: deploy/pulp/routes.yml
