- name: Manage the lifecycle of Foreman on OpenShift™
  hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - role: ansible-kubernetes-modules
  vars_files:
    - secrets.yml
  tasks:
    - import_tasks: deploy/project.yml
    - import_tasks: deploy/secrets.yml
    - import_tasks: deploy/services.yml
    - import_tasks: deploy/deployments.yml
    - import_tasks: deploy/persistent_volume_claims.yml
    - import_tasks: deploy/routes.yml
