- name: Manage the lifecycle of Foreman on OpenShift™
  hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - role: ansible-kubernetes-modules
  vars_files:
    - secrets.yml
  vars:
    minishift: true
    pulp_worker_count: 2
    registry: projgriffin
    foreman_providers: false
  tasks:
    - set_fact:
        deployment_state: present
      tags:
        - restart
        - start
        - stop
    - set_fact:
        deployment_state: absent
      tags:
        - destroy
    - set_fact:
        project_name: "{{ project_name | default('foreman') }}"
      tags:
        - always
    - set_fact:
        application_hostname: "{{ application_hostname | default('') }}"
      tags:
        - always
    - set_fact:
        application_hostname: "foreman.{{ lookup('pipe', 'minishift ip') }}.nip.io"
      when: application_hostname == '' and minishift == true
      tags:
        - always

    - import_tasks: deploy/project.yml

    - import_tasks: deploy/secrets/secrets.yml
    - import_tasks: deploy/foreman/config-maps.yml

    - import_tasks: deploy/service_accounts.yml

    - import_tasks: deploy/foreman/persistent_volume_claims.yml
    - import_tasks: deploy/postgres/persistent_volume_claims.yml
    - import_tasks: deploy/pulp/persistent_volume_claims.yml

    - import_tasks: deploy/candlepin/services.yml
    - import_tasks: deploy/foreman-proxy/services.yml
    - import_tasks: deploy/foreman/services.yml
    - import_tasks: deploy/postgres/services.yml
    - import_tasks: deploy/pulp/services.yml
    - import_tasks: deploy/puppet/services.yml
    - import_tasks: deploy/qpid/services.yml

    - import_tasks: deploy/foreman/jobs.yml

    - import_tasks: deploy/candlepin/deployments.yml
    - import_tasks: deploy/foreman-proxy/deployments.yml
    - import_tasks: deploy/foreman/deployments.yml
    - import_tasks: deploy/postgres/deployments.yml
    - import_tasks: deploy/pulp/deployments.yml
    - import_tasks: deploy/puppet/deployments.yml
    - import_tasks: deploy/qpid/deployments.yml

    - import_tasks: deploy/foreman/routes.yml
