---
- name: 'Generate certificates'
  hosts: localhost
  vars:
    certificates_ca_directory: certs
    certificates_services:
      - name: pulp
      - name: pulp-client
        common_name: admin
    content_server_hostname: "content-server-8080-foreman.{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.xip.io"
  roles:
    - certificates

- name: 'Build secrets file'
  hosts: localhost
  gather_facts: no
  tasks:
    - name:
      set_fact:
        certs: "{{ certs|default({}) | combine({ item.replace('.', '_').replace('-', '_'): lookup('file', 'certs/certs/' + item) }) }}"
      with_items:
        - ca.crt
        - pulp.crt
        - pulp-client.crt

    - name:
      set_fact:
        keys: "{{ keys|default({}) | combine({ item.replace('.', '_').replace('-', '_'): lookup('file', 'certs/private/' + item) }) }}"
      with_items:
        - ca.key
        - pulp.key
        - pulp-client.key

    - name: 'Write secrets to file'
      copy:
        content: "{{ certs | combine(keys) | to_nice_yaml }}"
        dest: ./secrets.yml
