---
apiVersion: v1
kind: Route
metadata:
  name: foreman-http-pulp
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: httpd
spec:
  host: "{{ application_hostname }}"
  path: /pulp
  to:
    kind: Service
    name: httpd
  port:
    targetPort: http
