---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: memcached
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: memcached
spec:
  template:
    metadata:
      labels:
        app: foreman
        service: memcached
    spec:
      containers:
        - name: memcached
          securityContext: {}
          state: present
          image: manageiq/memcached
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
