---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: memcached
spec:
  selector:
    app: foreman
    service: memcached
  ports:
    - protocol: TCP
      targetPort: 11211
      name: port-11211-tcp
      port: 11211
