---
- import_tasks: postgres/services.yml
- import_tasks: postgres/deployments.yml
- import_tasks: postgres/persistent_volume_claims.yml

- import_tasks: deploy/qpid/services.yml
- import_tasks: deploy/qpid/deployments.yml

- import_tasks: candlepin/secrets.yml
- import_tasks: candlepin/services.yml
- import_tasks: candlepin/deployments.yml
- import_tasks: candlepin/routes.yml
