---
robottelo_url: https://github.com/SatelliteQE/robottelo.git
robottelo_directory: /root/robottelo
robottelo_virtualenv_path: /root/robottelo/venv
robottelo_version: master
robottelo_test_arguments:
  - tests/foreman/endtoend/test_api_endtoend.py
