---
- name: Stop running containers by scaling replicas down to 0
  openshift_v1_deployment_config:
      name: pulp
      namespace: "{{ project_name }}"
      replicas: 0
  tags:
    - stop
    - restart
- name: Stop running containers by scaling replicas down to 0
  openshift_v1_deployment_config:
      name: pulp-worker
      namespace: "{{ project_name }}"
      replicas: 0
  tags:
    - stop
    - restart
- name: Stop running containers by scaling replicas down to 0
  openshift_v1_deployment_config:
      name: pulp-celerybeat
      namespace: "{{ project_name }}"
      replicas: 0
  tags:
    - stop
    - restart
- name: Stop running containers by scaling replicas down to 0
  openshift_v1_deployment_config:
      name: pulp-resource-manager
      namespace: "{{ project_name }}"
      replicas: 0
  tags:
    - stop
    - restart
- name: Stop running containers by scaling replicas down to 0
  openshift_v1_deployment_config:
      name: mongodb
      namespace: "{{ project_name }}"
      replicas: 0
  tags:
    - stop
    - restart
- name: Stop running containers by scaling replicas down to 0
  openshift_v1_deployment_config:
      name: content-server
      namespace: "{{ project_name }}"
      replicas: 0
  tags:
    - stop
    - restart
- name: Stop squid containers by scaling replicas down to 0
  openshift_v1_deployment_config:
      name: squid
      namespace: "{{ project_name }}"
      replicas: 0
  tags:
    - stop
    - restart
- name: Stop pulp-streamer containers by scaling replicas down to 0
  openshift_v1_deployment_config:
      name: pulp-streamer
      namespace: "{{ project_name }}"
      replicas: 0
  tags:
    - stop
    - restart
- name: Create deployment, and scale replicas up
  openshift_v1_deployment_config:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: deployment_config
          metadata:
              name: pulp
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: pulp
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: pulp
                  spec:
                      containers:
                        - name: pulp
                          securityContext: {}
                          state: present
                          volumeMounts:
                            - readOnly: true
                              mountPath: /etc/pki/pulp/private
                              name: keys
                            - readOnly: true
                              mountPath: /etc/pki/pulp/certs
                              name: certs
                            - readOnly: false
                              mountPath: /var/lib/pulp
                              name: pulp-data
                            - readOnly: false
                              mountPath: /etc/puppet
                              name: puppet-data
                          args:
                            - /usr/bin/start_httpd.sh
                          command:
                            - /usr/bin/entrypoint.sh
                          image: "{{ registry }}/foreman-pulp:latest"
                      serviceAccount: anyuid
                      serviceAccountName: anyuid
                      volumes:
                        - name: keys
                          secret:
                              items:
                                - path: pulp.key
                                  key: pulp.key
                                - path: ca.key
                                  key: ca.key
                              secretName: keys
                        - secret:
                              items:
                                - path: ca.crt
                                  key: ca.crt
                                - path: pulp.crt
                                  key: pulp.crt
                              secretName: certs
                          name: certs
                        - name: pulp-data
                          persistentVolumeClaim:
                              claimName: pulp-data
                        - name: puppet-data
                          persistentVolumeClaim:
                              claimName: puppet-data
              replicas: 1
              strategy:
                  type: Rolling
  tags:
    - start
    - restart
    - destroy
- name: Create deployment, and scale replicas up
  openshift_v1_deployment_config:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: deployment_config
          metadata:
              name: pulp-worker
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: pulp-worker
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: pulp-worker
                  spec:
                      serviceAccount: anyuid
                      serviceAccountName: anyuid
                      containers:
                        - name: pulp-worker
                          securityContext: {}
                          state: present
                          command:
                            - /usr/bin/entrypoint.sh
                          volumeMounts:
                            - readOnly: false
                              mountPath: /var/lib/pulp
                              name: pulp-data
                            - readOnly: false
                              mountPath: /etc/puppet
                              name: puppet-data
                          image: "{{ registry }}/foreman-pulp-worker:latest"
                      volumes:
                        - name: pulp-data
                          persistentVolumeClaim:
                              claimName: pulp-data
                        - name: puppet-data
                          persistentVolumeClaim:
                              claimName: puppet-data
              replicas: "{{ pulp_worker_count }}"
              strategy:
                  type: Rolling
  tags:
    - start
    - restart
    - destroy
- name: Create deployment, and scale replicas up
  openshift_v1_deployment_config:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: deployment_config
          metadata:
              name: pulp-celerybeat
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: pulp-celerybeat
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: pulp-celerybeat
                  spec:
                      containers:
                        - name: pulp-celerybeat
                          securityContext: {}
                          state: present
                          command:
                            - /usr/bin/entrypoint.sh
                          image: "{{ registry }}/foreman-pulp-celerybeat:latest"
                      serviceAccount: anyuid
                      serviceAccountName: anyuid
              replicas: 1
              strategy:
                  type: Rolling
  tags:
    - start
    - restart
    - destroy
- name: Create deployment, and scale replicas up
  openshift_v1_deployment_config:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: deployment_config
          metadata:
              name: pulp-resource-manager
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: pulp-resource-manager
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: pulp-resource-manager
                  spec:
                      containers:
                        - name: pulp-resource-manager
                          securityContext: {}
                          state: present
                          command:
                            - /usr/bin/entrypoint.sh
                          image: "{{ registry }}/foreman-pulp-resource-manager:latest"
                      serviceAccount: anyuid
                      serviceAccountName: anyuid
              replicas: 1
              strategy:
                  type: Rolling
  tags:
    - start
    - restart
    - destroy
- name: Create deployment, and scale replicas up
  openshift_v1_deployment_config:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: deployment_config
          metadata:
              name: mongodb
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: mongodb
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: mongodb
                  spec:
                      containers:
                        - name: mongodb
                          securityContext: {}
                          state: present
                          env:
                            - name: MONGODB_USER
                              value: admin
                            - name: MONGODB_PASSWORD
                              value: admin
                            - name: MONGODB_DATABASE
                              value: pulp_database
                            - name: MONGODB_ADMIN_PASSWORD
                              value: admin
                          args:
                            - run-mongod
                          volumeMounts:
                            - readOnly: false
                              mountPath: /var/lib/mongodb/data
                              name: mongodb-data
                          image: "{{ registry }}/foreman-mongodb:latest"
                      volumes:
                        - name: mongodb-data
                          persistentVolumeClaim:
                              claimName: mongodb-data
              replicas: 1
              strategy:
                  type: Rolling
  tags:
    - start
    - restart
    - destroy
- name: Create deployment, and scale replicas up
  openshift_v1_deployment_config:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: deployment_config
          metadata:
              name: content-server
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: content-server
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: content-server
                  spec:
                      containers:
                        - name: content-server
                          securityContext: {}
                          state: present
                          volumeMounts:
                            - readOnly: true
                              mountPath: /etc/pki/pulp/private
                              name: keys
                            - readOnly: true
                              mountPath: /etc/pki/pulp/certs
                              name: certs
                            - readOnly: false
                              mountPath: /var/lib/pulp
                              name: pulp-data
                          args:
                            - /usr/bin/start_httpd.sh
                          ports:
                            - protocol: TCP
                              containerPort: 8080
                          image: "{{ registry }}/foreman-content-server:latest"
                      serviceAccount: anyuid
                      serviceAccountName: anyuid
                      volumes:
                        - secret:
                              items:
                                - path: pulp.key
                                  key: pulp.key
                              secretName: keys
                          name: keys
                        - secret:
                              items:
                                - path: ca.crt
                                  key: ca.crt
                                - path: pulp.crt
                                  key: pulp.crt
                              secretName: certs
                          name: certs
                        - name: pulp-data
                          persistentVolumeClaim:
                              claimName: pulp-data
              replicas: 1
              strategy:
                  type: Rolling
  tags:
    - start
    - restart
    - destroy
- name: Create Squid deployment and scale up
  openshift_v1_deployment_config:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: deployment_config
          metadata:
              name: squid
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: squid
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: squid
                  spec:
                      containers:
                        - name: squid
                          securityContext: {}
                          state: present
                          command:
                            - /usr/bin/entrypoint.sh
                          args:
                            - /usr/bin/start_squid.sh
                          ports:
                            - protocol: TCP
                              containerPort: 3128
                          image: "{{ registry }}/foreman-squid:latest"
                      serviceAccount: anyuid
                      serviceAccountName: anyuid
              replicas: 1
              strategy:
                  type: Rolling
  tags:
    - start
    - restart
    - destroy
- name: Create Pulp Streamer deployment and scale up
  openshift_v1_deployment_config:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: deployment_config
          metadata:
              name: pulp-streamer
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: pulp-streamer
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: pulp-streamer
                  spec:
                      containers:
                        - name: pulp-streamer
                          securityContext: {}
                          state: present
                          args:
                            - /usr/bin/start_pulp_streamer.sh
                          ports:
                            - protocol: TCP
                              containerPort: 8751
                          image: "{{ registry }}/foreman-pulp-streamer:latest"
                      serviceAccount: anyuid
                      serviceAccountName: anyuid
              replicas: 1
              strategy:
                  type: Rolling
  tags:
    - start
    - restart
    - destroy
