---
katello_provisioning_hammer: hammer -u admin -p changeme
katello_provisioning_organization: Default Organization
katello_provisioning_organization_label: "{{ katello_provisioning_organization|regex_replace('\\s', '_') }}"
katello_provisioning_location: Default Location
katello_provisioning_foreman: True
katello_provisioning_katello: True
