---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: foreman-proxy
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: foreman-proxy
spec:
  template:
    metadata:
      labels:
        app: foreman
        service: foreman-proxy
    spec:
      containers:
        - name: foreman-proxy
          securityContext: {}
          state: present
          image: "{{ registry }}/foreman-proxy:latest"
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
      post:
        failurePolicy: Ignore
        execNewPod:
          containerName: foreman-proxy
          command:
            - /usr/bin/register.sh
