---
- name: Add Pulp repository
  yum_repository:
    name: pulp-repository
    description: Pulp release repository
    baseurl: "https://repos.fedorapeople.org/repos/pulp/pulp/{{ pulp_repositories_release }}/{{ pulp_repositories_version }}/7Server/x86_64/"
    gpgcheck: no
    enabled: yes

- name: 'Gofer repository'
  yum_repository:
    name: jortel-gofer
    description: Copr repo for gofer owned by jortel
    baseurl: https://copr-be.cloud.fedoraproject.org/results/jortel/gofer/epel-{{ ansible_distribution_major_version }}-x86_64/
    gpgcheck: 1
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/jortel/gofer/pubkey.gpg
