---
- name: 'Remove katello-repos'
  yum:
    name: katello-repos
    state: absent

- name: 'Katello Koji repository'
  yum_repository:
    name: katello-koji
    description: "Katello {{ foreman_proxy_content_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/katello-{{ foreman_proxy_content_version }}/katello/el7/x86_64/"
    priority: 1
    gpgcheck: 0

- name: 'Candlepin Koji repository'
  yum_repository:
    name: candlepin-koji
    description: "Candlepin {{ foreman_proxy_content_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/katello-{{ foreman_proxy_content_version }}/candlepin/el7/x86_64/"
    priority: 1
    gpgcheck: 0

- name: 'Pulp Koji repository'
  yum_repository:
    name: pulp-koji
    description: "Pulp {{ foreman_proxy_content_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/katello-{{ foreman_proxy_content_version }}/pulp/el7/x86_64/"
    priority: 1
    gpgcheck: 0
