---
- name: 'Install packages'
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-pulp-streamer

- name: 'Deploy pulp streamer conf'
  template:
    src: templates/streamer.conf.j2
    dest: /etc/pulp/streamer.conf

- name: 'Add pulp streamer console logging'
  get_url:
    url: https://raw.githubusercontent.com/ehelms/pulp/127d099833ec8d3c757db2b28b5fd14a2b6d7077/streamer/usr/share/pulp/wsgi/streamer.tac
    dest: /usr/share/pulp/wsgi/streamer.tac
    force: yes

- name: Copy entrypoint
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    mode: 0775
  with_items:
    - entrypoint.sh
    - start_pulp_streamer.sh
