---
- name: 'Update packages'
  yum:
    name: '*'
    update_cache: yes
    state: latest

- name: 'Install foreman-release-scl'
  yum:
    name: foreman-release-scl
    update_cache: yes
    state: latest

- name: 'Install Katello RPM'
  yum:
    name: katello
    state: latest

- name: 'Run installer'
  command: "{{ katello_installer_command }}"
  when: not katello_skip_installer
