---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: postgres
spec:
  selector:
    app: foreman
    service: postgres
  ports:
    - protocol: TCP
      targetPort: 5432
      name: port-5432-tcp
      port: 5432
