---
- name: "Add dynflowd startup script"
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    mode: 0775
  with_items:
    - wait_on_migrations.py
    - entrypoint.sh
    - start-dynflowd.sh
