---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: qpid
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: qpid
spec:
  template:
    metadata:
      labels:
        app: foreman
        service: qpid
    spec:
      containers:
        - name: qpid
          securityContext: {}
          state: present
          image: "{{ registry }}/qpid:latest"
      serviceAccount: "{{ project_name }}-anyuid"
      serviceAccountName: "{{ project_name }}-anyuid"
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
