---
- name: 'Install foreman-sqlite'
  yum:
    name: foreman-sqlite
    state: installed

- name: 'Deploy build database.yml'
  copy:
    src: "{{ role_path }}/files/build/database.yml"
    dest: "/etc/foreman/database.yml"

- name: 'Create build database'
  command: 'foreman-rake db:create'

- name: 'Migrate build database'
  command: 'foreman-rake db:migrate'

- name: 'Generate apipie:cache:index'
  command: 'foreman-rake apipie:cache:index'

- name: 'Remove foreman-sqlite'
  yum:
    name: foreman-sqlite
    state: absent
