# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
---
- hosts: foreman
  vars:
    puppet_repositories_version: 4
  roles:
    - epel-repositories
    - puppet-repositories
    - foreman-repositories
    - katello-repositories
    - foreman

- hosts: foreman-tasks
  vars:
    puppet_repositories_version: 4
  roles:
    - epel-repositories
    - puppet-repositories
    - foreman-repositories
    - katello-repositories
    - foreman
    - foreman-tasks

- hosts: pulp
  roles:
    - epel-repositories
    - katello-repositories
    - pulp

- hosts: pulp-worker
  roles:
    - epel-repositories
    - katello-repositories
    - pulp
    - pulp-worker

- hosts: pulp-resource-manager
  roles:
    - epel-repositories
    - katello-repositories
    - pulp
    - pulp-resource-manager

- hosts: pulp-celerybeat
  roles:
    - epel-repositories
    - katello-repositories
    - pulp
    - pulp-celerybeat

- hosts: cp-app
  roles:
    - epel-repositories
    - katello-repositories
    - candlepin

- hosts: qpid
  roles:
    - epel-repositories
    - qpid

- hosts: foreman-proxy
  roles:
    - epel-repositories
    - foreman-repositories
    - foreman-proxy

- hosts: foreman-proxy-register
  roles:
    - epel-repositories
    - foreman-repositories
    - foreman-proxy
