- hosts: localhost
  vars:
    forklift_name: pipeline-katello-3.1
    forklift_boxes:
      pipeline-katello-3.1-centos7:
        box: centos7
        memory: 4680
      pipeline-proxy-3.1-centos7:
        box: centos7
        memory: 3072
  roles:
    - forklift

- hosts:
  - pipeline-katello-3.1-centos7
  - pipeline-proxy-3.1-centos7
  become: yes
  vars:
    katello_repositories_version: 3.1
    foreman_repositories_version: 1.12
    katello_repositories_use_koji: true
    foreman_installer_skip_installer: true
  roles:
    - etc_hosts
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - disable_firewall
    - haveged
    - update_os_packages
    - foreman_installer

- hosts: pipeline-katello-3.1-centos7
  become: yes
  vars:
    foreman_installer_scenario: katello
    foreman_installer_options_internal_use_only:
      - "--foreman-admin-password {{ foreman_installer_admin_password }}"
    foreman_installer_additional_packages:
      - katello
  roles:
    - foreman_installer

- hosts: pipeline-capsule-3.1-centos7
  become: yes
  vars:
    capsule_server: pipeline-katello-3.1-centos7
    foreman_installer_scenario: capsule
    foreman_installer_options_internal_use_only:
      - '--foreman-proxy-trusted-hosts "{{ server_fqdn.stdout }}"
        --foreman-proxy-trusted-hosts "{{ ansible_nodename }}"
        --foreman-proxy-foreman-base-url "https://{{ server_fqdn.stdout }}"
        --foreman-proxy-register-in-foreman true
        --foreman-proxy-oauth-consumer-key "{{ oauth_consumer_key.stdout }}"
        --foreman-proxy-oauth-consumer-secret "{{ oauth_consumer_secret.stdout }}"
        --capsule-certs-tar "{{ capsule_certs_tar }}"
        --capsule-parent-fqdn "{{ server_fqdn.stdout }}"
        --capsule-pulp-oauth-secret "{{ pulp_oauth_secret.stdout }}"'
    foreman_installer_additional_packages:
      - foreman-installer-katello
  roles:
    - capsule
    - foreman_installer

- hosts: pipeline-katello-3.1-centos7
  become: true
  roles:
    - bats

- hosts: pipeline-capsule-3.1-centos7
  become: true
  vars:
    bats_tests:
      - fb-proxy.bats
  roles:
    - bats
