- hosts: localhost
  vars:
    forklift_name: pipeline-foreman-nightly
    forklift_boxes:
      pipeline-foreman-nightly-centos7:
        box: centos7
        memory: 4680
  roles:
    - forklift

- hosts:
  - pipeline-foreman-nightly-centos7
  become: yes
  vars:
    foreman_installer_options_internal_use_only:
      - "--foreman-admin-password {{ foreman_installer_admin_password }}"
      - "--puppet-server-max-active-instances 1"
      - "--puppet-server-jvm-min-heap-size 1G"
      - "--puppet-server-jvm-max-heap-size 1G"
    foreman_repositories_version: nightly
    foreman_repositories_environment: staging
    bats_tests:
      - "fb-verify-packages.bats"
      - "fb-test-foreman.bats"
      - "fb-test-puppet.bats"
    bats_teardown:
      - "fb-finish.bats"
  roles:
    - disable_firewall
    - swapfile
    - foreman
    - foreman_testing
