---
# make installation media available
# until it's done by seed - http://projects.theforeman.org/issues/22661
- name: 'assign organization and location to all seeded media'
  with_items:
    - CentOS mirror
    - CoreOS mirror
    - Debian mirror
    - Fedora Atomic mirror
    - Fedora mirror
    - FreeBSD mirror
    - OpenSUSE mirror
    - Ubuntu mirror
  shell: >
    {{ foreman_provisioning_hammer }} medium update --name "{{ item }}" --organization-titles "{{ foreman_provisioning_organization }}" --location-titles "{{ foreman_provisioning_location }}"
  when: foreman_provisioning_use_taxonomies and foreman_provisioning_foreman_version == 'nightly'


- name: 'Setup CentOS 7 provisioning'
  import_tasks: configure_centos_7.yml

- name: 'Setup Fedora 27 provisioning'
  import_tasks: configure_fedora_27.yml

- name: 'Setup Debian 9.3 provisioning'
  import_tasks: configure_debian_9_3.yml

- name: 'Setup Ubuntu 17.10 provisioning'
  import_tasks: configure_ubuntu_17_10.yml

# TODO verify - should not be needed, DNS should work just fine
- name: 'set unattended_url'
  shell: >
    {{ foreman_provisioning_hammer }} settings set --name unattended_url --value 'http://{{ foreman_provisioning_ip_address }}'

- name: 'find hostgroup Base'
  shell: >
    {{ foreman_provisioning_hammer }} hostgroup info --name 'Base'
  register: foreman_provisioning_hostgroup_base
  ignore_errors: True

- name: 'prepare compute resource option'
  set_fact:
    foreman_provisioning_compute_resource_option: "{{ '--compute-resource libvirt' if foreman_provisioning_foreman_version == 'nightly' else '' }}"

# TODO compute-profile can't be specified by name until http://projects.theforeman.org/issues/21580/ so we hardcode 1
- name: 'create hostgroup Base'
  shell: >
    {{ foreman_provisioning_hammer }} hostgroup create
    --name 'Base'
    --architecture x86_64
    --domain {{ foreman_provisioning_domain }}
    --environment production
    --puppet-ca-proxy-id {{ foreman_provisioning_smart_proxy.Id }}
    --puppet-proxy-id {{ foreman_provisioning_smart_proxy.Id }}
    --subnet '{{ foreman_provisioning_network }}/24'
    --compute-profile-id 1
    {{ foreman_provisioning_compute_resource_option }}
    --root-pass changeme
    --pxe-loader "PXELinux BIOS"
    {{ foreman_provisioning_hammer_taxonomy_params }}
  when: foreman_provisioning_hostgroup_base.stderr.find('not found') != -1

- name: 'find hostgroup CentOS 7'
  shell: >
    {{ foreman_provisioning_hammer }} hostgroup info --name 'CentOS 7 Mirror'
  register: foreman_provisioning_hostgroup_centos_mirror
  ignore_errors: True

- name: 'create hostgroup CentOS 7 Mirror'
  shell: >
    {{ foreman_provisioning_hammer }} hostgroup create
    --name 'CentOS 7 Mirror'
    --operatingsystem 'CentOS 7'
    --medium 'CentOS mirror'
    --partition-table 'Kickstart default'
    --parent 'Base'
    {{ foreman_provisioning_hammer_taxonomy_params }}
  when: foreman_provisioning_hostgroup_centos_mirror.stderr.find('not found') != -1
