---
- name: 'Install foreman compute packages'
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - foreman-ovirt
    - foreman-libvirt

- name: 'Clone foreman_providers'
  git:
    repo: https://github.com/agrare/foreman_providers.git
    dest: /root/foreman_providers
    version: link_compute_resources_and_providers
    update: yes

- name: 'Build gem'
  command: scl enable tfm "gem build *.gemspec"
  args:
    chdir: /root/foreman_providers

- name: 'Install foreman_providers'
  shell: scl enable tfm "gem install *.gem"
  args:
    chdir: /root/foreman_providers

- name: 'Install bundler file for foreman_providers'
  copy:
    content: "gem 'foreman_providers'"
    dest: /usr/share/foreman/bundler.d/providers.rb
