---
- name: 'Install Puppetlabs GPG key'
  apt_key:
    url: https://apt.puppetlabs.com/DEB-GPG-KEY-puppet

- name: 'Install Puppetlabs PC1 repository'
  apt_repository:
    repo: deb http://apt.puppetlabs.com {{ ansible_distribution_release }} PC1
    state: present
