---
- include: release_repos.yml
  when: foreman_repositories_use_release and not foreman_repositories_use_koji

- include: koji_repos.yml
  when: foreman_repositories_use_koji

- name: 'Install foreman-release-scl'
  yum:
    name: foreman-release-scl
    state: latest
  tags:
    - packages
