---
- name: 'Setup Foreman Repository'
  yum:
    name: http://yum.theforeman.org/{{ "releases/" if foreman_repositories_version != 'nightly' else '' }}{{ foreman_repositories_version }}/el{{ ansible_distribution_major_version }}/x86_64/foreman-release.rpm
    state: present
  tags:
    - packages
