---
- name: Create secret for private keys
  k8s_v1_secret:
      state: present
      force: false
      resource_definition:
          apiVersion: v1
          kind: Secret
          metadata:
              name: keys
              namespace: "{{ project_name }}"
          type: Opaque
          data:
              ca.key: '{{ ca_key | b64encode }}'
              pulp.key: '{{ pulp_key | b64encode }}'
              pulp-client.key: '{{ pulp_client_key | b64encode }}'
              server.key: '{{ server_key | b64encode }}'

- name: Create secret for CA cert and key
  k8s_v1_secret:
      state: present
      force: false
      resource_definition:
          apiVersion: v1
          kind: Secret
          metadata:
              name: ca
              namespace: "{{ project_name }}"
          type: Opaque
          data:
              ca.crt: '{{ ca_crt | b64encode }}'
              ca.key: '{{ ca_key | b64encode }}'

- name: Create secret for certificates
  k8s_v1_secret:
      state: present
      force: false
      resource_definition:
          apiVersion: v1
          kind: Secret
          metadata:
              name: certs
              namespace: "{{ project_name }}"
          type: Opaque
          data:
              ca.crt: '{{ ca_crt | b64encode }}'
              pulp-client.crt: '{{ pulp_client_crt | b64encode }}'
              pulp.crt: '{{ pulp_crt | b64encode }}'
              server.crt: '{{ server_crt | b64encode }}'
