---
- hosts: all
  gather_facts: no
  vars_files:
    - ../vars/local.yml
  tasks:
    - name: 'Run build'
      shell: "ansible-container --devel build {{ '--services' if services else '' }} {{ services }}"
      args:
        chdir: "{{ working_dir }}"
