---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: 'Build image'
      command: "docker build -t {{ image }}:latest ."
      args:
        chdir: "../images/{{ image }}"
      tags:
        - build

    - name: 'Tag image'
      command: "docker tag {{ image }} quay.io/foreman/{{ image }}:latest"
      tags:
        - push

    - name: 'Push image'
      command: "docker push quay.io/foreman/{{ image }}:latest"
      tags:
        - push
