---
- hosts: all
  gather_facts: no
  tasks:
    - slurp:
        src: "{{ certificates_ca_directory + '/certs/' + item }}"
      register: cert_files
      with_items:
        - ca.crt
        - pulp.crt
        - pulp-client.crt

    - name:
      set_fact:
        certs: "{{ certs|default({}) | combine({item.item.replace('.', '_').replace('-', '_'): item.content | b64decode}) }}"
      with_items:
        - "{{ cert_files.results }}"

    - slurp:
        src: "{{ certificates_ca_directory + '/private/' + item }}"
      register: key_files
      with_items:
        - ca.key
        - pulp.key
        - pulp-client.key

    - name:
      set_fact:
        keys: "{{ keys|default({}) | combine({item.item.replace('.', '_').replace('-', '_'): item.content | b64decode}) }}"
      with_items:
        - "{{ key_files.results }}"

    - name: 'Write secrets to file'
      copy:
        content: "{{ certs | combine(keys) | to_nice_yaml }}"
        dest: "{{ working_dir  }}/secrets.yml"
