---
- hosts: all
  gather_facts: yes
  vars_files:
    - ../vars/local.yml
  tasks:
    - name: 'Check  cluster status'
      command: 'oc cluster status'
      register: cluster_status
      ignore_errors: true

    - name: "Spin cluster up"
      command: >
        oc cluster up
          --host-data-dir={{ openshift_data_dir }}/openshift.local.config
          --host-pv-dir={{ openshift_data_dir }}/openshift.local.pv
          --host-volumes-dir={{ openshift_data_dir }}/openshift.local.volumes
          --public-hostname={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
      when: cluster_status | failed
      register: cluster_up
