---
- hosts: all
  gather_facts: no
  tasks:
    - name: 'Deploy to Openshift'
      command: 'ansible-playbook -l localhost ansible-deployment/foreman.yml --tags start'
      args:
        chdir: "{{ working_dir }}"
