---
- hosts: all
  gather_facts: no
  tasks:
    - name: 'Install git'
      package:
        name: git
        state: present

    - name: 'Install epel'
      package:
        name: epel-release
        state: present

    - name: 'Update setuptools'
      command: 'pip install setuptools --upgrade'

    - name: 'Install openshift'
      pip:
        name: openshift

    - name: 'Get minishift oc-env'
      command: minishift oc-env
      register: oc_env

    - name: Add another bin dir to system-wide $PATH.
      copy:
        dest: /etc/profile.d/oc-env.sh
        content: "{{ oc_env.stdout }}"

    - name: 'Get minishift docker-env'
      command: minishift docker-env
      register: docker_env

    - name: Add another bin dir to system-wide $PATH.
      copy:
        dest: /etc/profile.d/docker-env.sh
        content: "{{ docker_env.stdout }}"

- hosts: all
  gather_facts: no
  tasks:
    - name: 'Deploy to Openshift'
      command: 'ansible-playbook -l localhost foreman.yml'
      args:
        chdir: "{{ working_dir }}"
