---
- hosts: all
  gather_facts: no
  tasks:
    - name: 'Check for Foreman project'
      command: oc project foreman
      register: project_exists
      ignore_errors: true

    - name: 'Create Foreman project'
      command: oc new-project foreman
      when: project_exists | failed

    - name: 'Get Openshift token'
      command: 'oc whoami -t'
      register: token

    - name: 'Generate deployment role'
      command: "ansible-container --devel --engine openshift deploy --push-to {{ registry }} --username developer --password {{ token.stdout }} --tag latest"
      args:
        chdir: "{{ working_dir }}"

    - name: 'Copy secrets file'
      copy:
        src: "{{ working_dir }}/secrets.yml"
        dest: "{{ working_dir }}/ansible-deployment/secrets.yml"
        remote_src: yes
