---
- hosts: all
  gather_facts: no
  vars_files:
    - ../vars/local.yml
  vars:
    openshift_version: v3.7.1
    openshift_checksum: ab0f056
  tasks:
    - name: 'Create .tmp directory'
      file:
        path: "{{ working_dir }}/.tmp"
        state: directory

    - name: 'Download OpenShift client tools'
      unarchive:
        src: "https://github.com/openshift/origin/releases/download/{{ openshift_version }}/openshift-origin-server-{{ openshift_version }}-{{ openshift_checksum }}-linux-64bit.tar.gz"
        dest: "{{ working_dir }}/.tmp/"
        creates: "{{ working_dir }}/.tmp/openshift-origin-server-{{ openshift_version }}-{{ openshift_checksum }}-linux-64bit"
        remote_src: yes

    - name: 'Create local bin'
      file:
        path: "{{ bin_dir }}"
        state: directory

    - name: 'Link CLI to local bin'
      file:
        state: link
        src: "{{ working_dir }}/.tmp/openshift-origin-server-{{ openshift_version }}-{{ openshift_checksum }}-linux-64bit/oc"
        dest: "{{ bin_dir }}/oc"

    - name: 'Link oadm to local bin'
      file:
        state: link
        src: "{{ working_dir }}/.tmp/openshift-origin-server-{{ openshift_version }}-{{ openshift_checksum }}-linux-64bit/oadm"
        dest: "{{ bin_dir }}/oadm"
