---
- hosts: all
  roles:
    - epel_repositories
  tasks:
    - name: 'Install pip'
      package:
        name: python2-pip
        state: present

    - name: 'Install Ansible'
      pip:
        name: 'ansible'

    - name: 'Install rsync'
      package:
        name: 'rsync'
        state: present

    - name: 'Copy forklift to node'
      synchronize:
        src: "{{ lookup('pipe', 'pwd') }}/../../"
        dest: "{{ project_dir }}"
