---
- hosts: all
  vars_files:
    - ../vars/local.yml
  tasks:
    - name: 'Install pip'
      become: true
      package:
        name: python-pip
        state: present

    - name: 'Update setuptools'
      become: true
      pip:
        name: setuptools
        state: latest

    - name: 'Install git'
      become: true
      package:
        name: git
        state: present

    - name: 'Create .tmp directory'
      file:
        path: "{{ working_dir }}/.tmp"
        state: directory

    - name: 'Clone ansible-container'
      git:
        repo: https://github.com/ansible/ansible-container.git
        dest: "{{ working_dir }}/.tmp/ansible-container"
        update: yes
        force: yes

    - name: 'Install ansible-container'
      become: true
      command: "pip2 install -e .[docker,openshift] --upgrade"
      args:
        chdir: "{{ working_dir }}/.tmp/ansible-container"
