---
- name: 'Clone the hammer repositories'
  git:
    repo: https://github.com/{{ item }}.git
    dest: ~/{{ item.split('/')[1] }}
    update: no
    remote: upstream
  with_items: "{{ hammer_devel_repositories }}"

- name: 'Check if the fork remotes exist'
  shell: "git remote | grep ^{{ hammer_devel_github_fork_remote_name }}$"
  args:
    chdir: ~/{{ item.split('/')[1] }}
  ignore_errors: yes
  with_items: "{{ hammer_devel_repositories }}"
  register: fork_remotes_exist

- name: 'Add fork remotes to cloned repositories'
  command: "git remote add {{ hammer_devel_github_fork_remote_name }} git@github.com:{{ hammer_devel_github_username }}/{{ item.item.split('/')[1] }}.git"
  when: item.rc != 0
  args:
    chdir: ~/{{ item.item.split('/')[1] }}
  with_items: "{{ fork_remotes_exist.results }}"

- name: 'Add local gems to Gemfile.local'
  blockinfile:
    dest: ~/hammer-cli-katello/Gemfile.local
    create: yes
    block: |
      gem 'pry'
      path '../' do
        gem 'hammer_cli'
        gem 'hammer_cli_foreman'
        gem 'hammer_cli_foreman_admin'
        gem 'hammer_cli_foreman_tasks'
        gem 'hammer_cli_csv'
      end

- name: 'Install gem native dependencies'
  become: true
  yum: name=gcc-c++ state=present

- name: 'Install bundler'
  gem: name=bundler state=present

- name: 'Install gems'
  bundler: chdir=~/hammer-cli-katello state=present executable=~/bin/bundle
