---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: puppet
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: puppet
spec:
  template:
    metadata:
      labels:
        app: foreman
        service: puppet
    spec:
      containers:
        - name: puppet
          securityContext: {}
          state: present
          volumeMounts:
            - readOnly: false
              mountPath: /etc/puppet
              name: puppet-data
          image: puppet/puppetserver
      serviceAccount: "{{ project_name }}-anyuid"
      serviceAccountName: "{{ project_name }}-anyuid"
      volumes:
        - name: puppet-data
          persistentVolumeClaim:
            claimName: puppet-data
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
