---
- name: 'Setup Epel Repository'
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  tags:
    - packages
  when: ansible_os_family == 'RedHat'

- name: 'Enable CentOS-CR Repository'
  ini_file:
    path: /etc/yum.repos.d/CentOS-CR.repo
    section: cr
    option: enabled
    value: 1
    no_extra_spaces: True
  tags:
    - packages
  when: ansible_distribution == 'CentOS'
