---
- include: devel_install.yml
  when: (foreman_proxy_content_upgrade == False and devel is defined and devel == True)

- include: install.yml
  when: foreman_proxy_content_upgrade == False

- include: upgrade.yml
  when: foreman_proxy_content_upgrade == True
