---
- include_tasks: certs_generate.yml

- name: 'Run installer upgrade'
  command: >
    foreman-installer
    -v
    --scenario foreman-proxy-content
    --disable-system-checks
    --upgrade
    --certs-update-all
    --certs-regenerate=true
    --certs-deploy=true
    --foreman-proxy-content-certs-tar="{{ foreman_proxy_content_certs_tar }}"
