---
- name: Create celery directory
  file:
    state: directory
    path: /var/lib/pulp/celery
    mode: 0777

- name: Copy entrypoint
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    mode: 0775
  with_items:
    - entrypoint.sh
