---
hammer_devel_ruby_version: 2.3.1
hammer_devel_server_group: "server-{{ inventory_hostname }}"
hammer_devel_server: "centos7-devel"
hammer_devel_server_protocol: 'https'
hammer_devel_server_port: 443
hammer_devel_host: "{{ hammer_devel_server_protocol }}://{{ hammer_devel_server }}:{{ hammer_devel_server_port }}"
hammer_devel_username: admin
hammer_devel_password: changeme
hammer_devel_repositories:
  - theforeman/hammer-cli
  - theforeman/hammer-cli-foreman
  - theforeman/hammer-cli-foreman-admin
  - theforeman/hammer-cli-foreman-tasks
  - katello/hammer-cli-csv
  - katello/hammer-cli-katello
