---
- name: 'Add /etc/hosts record for FreeIPA'
  become: true
  delegate_to: "{{ katello_server_ip }}"
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ ansible_nodename }}$"
    line: "{{ freeipa_server_ip }} {{ ansible_nodename }}"
    state: present

- name: 'Install FreeIPA client and admintools'
  become: true
  delegate_to: "{{ katello_server_ip }}"
  yum:
    name: ipa-client,ipa-admintools
    state: latest

- name: 'Register Foreman in FreeIPA'
  become: true
  delegate_to: "{{ katello_server_ip }}"
  shell: ipa-client-install --domain {{ ansible_domain }} --server {{ ansible_nodename }} --mkhomedir --fixed-primary --realm={{ freeipa_server_realm }} --force-join -p {{ freeipa_server_kerberos_principal }}@{{ freeipa_server_realm }} -w {{ freeipa_server_realm_password }} -U creates=/etc/krb5.keytab

- name: 'Run foreman-prepare-realm'
  become: true
  delegate_to: "{{ katello_server_ip }}"
  shell: echo changeme | foreman-prepare-realm {{ freeipa_server_kerberos_principal }}@{{ freeipa_server_realm }} {{ katello_server }}.{{ freeipa_server_domain }} chdir=/root creates=/root/freeipa.keytab

- name: 'Create HTTP principal'
  become: true
  delegate_to: "{{ katello_server_ip }}"
  shell: echo changeme | kinit {{ freeipa_server_kerberos_principal }}

- name: 'Add the host'
  become: true
  delegate_to: "{{ katello_server_ip }}"
  shell: ipa host-show   {{ katello_server }}.{{ freeipa_server_domain }} || ipa host-add --ip-address {{ ansible_eth0.ipv4.address }} {{ katello_server }}.{{ freeipa_server_domain }}

- name: 'Add the service'
  become: true
  delegate_to: "{{ katello_server_ip }}"
  shell: ipa service-show HTTP/{{ katello_server }}.{{ freeipa_server_domain }} || ipa service-add HTTP/{{ katello_server }}.{{ freeipa_server_domain }} --force

- name: 'Get the keytab'
  become: true
  delegate_to: "{{ katello_server_ip }}"
  shell: test -e /etc/httpd/conf/ipa.keytab  || ipa-getkeytab -s {{ ansible_nodename }} -p HTTP/{{ katello_server }}.{{ freeipa_server_domain }}@{{ freeipa_server_realm }} -k /etc/httpd/conf/ipa.keytab

- name: 'Copy the keytab'
  become: true
  delegate_to: "{{ katello_server_ip }}"
  shell: test -e /root/freeipa.keytab && cp /root/freeipa.keytab /etc/foreman-proxy/freeipa.keytab && chown foreman-proxy /etc/foreman-proxy/freeipa.keytab && chmod 0600 /etc/foreman-proxy/freeipa.keytab

- name: 'Enable Realm with foreman-installer'
  become: true
  delegate_to: "{{ katello_server_ip }}"
  shell: foreman-installer --foreman-proxy-realm=true --disable-system-checks
