---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: mongodb
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: mongodb
spec:
  template:
    metadata:
      labels:
        app: foreman
        service: mongodb
    spec:
      containers:
        - name: mongodb
          securityContext: {}
          state: present
          env:
            - name: MONGODB_USER
              value: admin
            - name: MONGODB_PASSWORD
              value: admin
            - name: MONGODB_DATABASE
              value: pulp_database
            - name: MONGODB_ADMIN_PASSWORD
              value: admin
          args:
            - run-mongod
          volumeMounts:
            - readOnly: false
              mountPath: /var/lib/mongodb/data
              name: mongodb-data
          image: "centos/mongodb-34-centos7:latest"
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
