---
- name: 'install libvirt gem'
  yum: name=rubygem-ruby-libvirt state=present

- name: 'install foreman-libvirt'
  yum: name=foreman-libvirt state=present

- name: 'enable provisioning with foreman-installer'
  shell: >
    foreman-installer
    --disable-system-checks
    --foreman-proxy-dns true
    --foreman-proxy-dns-provider libvirt
    --foreman-proxy-dns-interface virbr1
    --foreman-proxy-dns-zone example.com
    --foreman-proxy-dns-forwarders 8.8.8.8
    --foreman-proxy-dns-reverse 73.168.192.in-addr.arpa
    --foreman-proxy-dhcp true
    --foreman-proxy-dhcp-provider libvirt
    --foreman-proxy-libvirt-network provision
    --foreman-proxy-dhcp-interface virbr1
    --foreman-proxy-dhcp-range "192.168.73.2 192.168.73.100"
    --foreman-proxy-dhcp-gateway 192.168.73.1
    --foreman-proxy-dhcp-nameservers 192.168.73.1
    --foreman-proxy-tftp-servername 192.168.73.1
    --foreman-proxy-tftp true
    --foreman-proxy-tftp-managed false

- name: 'restart foreman-proxy'
  service: name=foreman-proxy state=restarted

- name: 'restart foreman'
  service: name=httpd state=restarted

- name: 'refresh features'
  shell: >
    {{ katello_provisioning_hammer }} proxy refresh-features --id {{ katello_provisioning_smart_proxy.Id }}

# Compute Resource
- name: 'find compute resource'
  shell: >
    {{ katello_provisioning_hammer }} compute-resource info --name "libvirt"
  register: katello_provisioning_compute_resource
  ignore_errors: True

- name: 'create compute resource'
  shell: >
    {{ katello_provisioning_hammer }} compute-resource create
    --name "libvirt"
    --url "qemu:///system"
    --provider libvirt
    --organizations "{{ katello_provisioning_organization }}"
    --locations "{{ katello_provisioning_location }}"
  when: katello_provisioning_compute_resource.stderr.find('not found') != -1

# Domain
- name: 'find domain'
  shell: >
    {{ katello_provisioning_hammer }} domain info --name "example.com"
  register: katello_provisioning_domain
  ignore_errors: True

- name: 'create domain'
  shell: >
    {{ katello_provisioning_hammer }} domain create
    --name example.com
    --dns-id {{ katello_provisioning_smart_proxy.Id }}
    --organizations "{{ katello_provisioning_organization }}"
    --locations "{{ katello_provisioning_location }}"
  when: katello_provisioning_domain.stderr.find('not found') != -1

- name: 'update domain'  # it may have been automatically created by puppet if katello reports first
  shell: >
    {{ katello_provisioning_hammer }} domain update
    --name example.com
    --dns-id {{ katello_provisioning_smart_proxy.Id }}
    --organizations "{{ katello_provisioning_organization }}"
    --locations "{{ katello_provisioning_location }}"

# Subnet
- name: 'find subnet'
  shell: >
    {{ katello_provisioning_hammer }} subnet info --name "192.168.73.0/24"
  register: katello_provisioning_subnet
  ignore_errors: True

- name: 'create subnet'
  shell: >
    {{ katello_provisioning_hammer }} subnet create
    --name "192.168.73.0/24"
    --dhcp-id {{ katello_provisioning_smart_proxy.Id }}
    --dns-id {{ katello_provisioning_smart_proxy.Id }}
    --tftp-id {{ katello_provisioning_smart_proxy.Id }}
    --domains example.com
    --from 192.168.73.2
    --to 192.168.73.100
    --network 192.168.73.0
    --mask 255.255.255.0
    --ipam DHCP
    --gateway 192.168.73.1
    --dns-primary 192.168.73.1
    --organizations "{{ katello_provisioning_organization }}"
    --locations "{{ katello_provisioning_location }}"
  when: katello_provisioning_subnet.stderr.find('not found') != -1

# Puppet
- name: 'find environment'
  shell: >
    {{ katello_provisioning_hammer }} environment info --name "production"
  register: katello_provisioning_environment
  ignore_errors: True

- name: 'create environment'
  shell: >
    {{ katello_provisioning_hammer }} environment create
    --name production
    --organizations "{{ katello_provisioning_organization }}"
    --locations "{{ katello_provisioning_location }}"
  when: katello_provisioning_environment.stderr.find('not found') != -1

- name: 'update environment'  # it may have been automatically created by puppet if katello reports first
  shell: >
    {{ katello_provisioning_hammer }} environment update
    --name production
    --organizations "{{ katello_provisioning_organization }}"
    --locations "{{ katello_provisioning_location }}"

# query local nameservers http://projects.theforeman.org/issues/13419
- name: 'query local nameservers'
  shell: >
    {{ katello_provisioning_hammer }} settings set --name query_local_nameservers --value true
