---
- name: Scale Foreman Proxy to 0
  openshift_v1_deployment_config:
      name: foreman-proxy
      namespace: "{{ project_name }}"
      replicas: 0
  tags:
    - stop
    - restart

- name: Create Foreman Proxy deployment
  openshift_v1_deployment_config:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: deployment_config
          metadata:
              name: foreman-proxy
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: foreman-proxy
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: foreman-proxy
                  spec:
                      containers:
                        - name: foreman-proxy
                          securityContext: {}
                          state: present
                          image: "{{ registry }}/foreman-proxy:latest"
              replicas: 1
              strategy:
                  type: Rolling
                  rollingParams:
                      timeoutSeconds: 900
                      post:
                        failurePolicy: Ignore
                        execNewPod:
                          containerName: foreman-proxy
                          command:
                            - /usr/bin/register.sh
  tags:
    - start
    - restart
    - destroy
