---
- name: Create service
  k8s_raw:
      state: "{{ deployment_state }}"
      force: false
      definition:
          apiVersion: v1
          kind: Service
          metadata:
              name: foreman-proxy
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: foreman-proxy
          spec:
              selector:
                  app: foreman
                  service: foreman-proxy
              ports:
                - protocol: TCP
                  targetPort: 8080
                  name: port-8080-tcp
                  port: 8080
  tags:
    - start
    - destroy
