---
- hosts: localhost
  vars:
    #registry: http://172.30.1.1:5000
    registry: oc-cluster
    project: foreman
  tasks:
    - name: 'Get Openshift token'
      command: 'oc whoami -t'
      register: token

    - name: 'Push images to Openshift'
      #command: "ansible-container push --push-to {{ registry }}/{{ project }} --username developer --password {{ token.stdout }}"
      command: "ansible-container push --push-to {{ registry }} --username developer --password {{ token.stdout }}"

    - name: 'Generate deployment role'
      command: "ansible-container shipit openshift --pull-from {{ registry }}"

    - name: 'Deploy to Openshift'
      command: "ansible-playbook ansible/shipit-openshift.yml"
      register: shipit_output
      ignore_errors: true

    - debug:
        msg: "{{ shipit_output.stdout.split('\n') }}"
