---
- hosts: localhost
  gather_facts: no
  vars:
    registry: oc-cluster
  tasks:
    - name: 'Get Openshift token'
      command: 'oc whoami -t'
      register: token

    - name: 'Generate deployment role'
      command: "ansible-container --engine openshift deploy --push-to {{ registry }} --username developer --password {{ token.stdout }} --tag latest"

      #- name: 'Install kubernetes-modules role'
      #command: 'ansible-galaxy install -r requirements.yml -p ansible-deployment/'

    - name: 'Deploy to Openshift'
      command: "ansible-playbook ansible-deployment/foreman.yml --tags start"
      register: shipit_output
      ignore_errors: true

    - debug:
        msg: "{{ shipit_output.stdout.split('\n') }}"
