---
- name: Create Pub PVC
  k8s_raw:
      state: "{{ deployment_state }}"
      force: false
      definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
              name: pub-data
              namespace: "{{ project_name }}"
          spec:
              resources:
                  requests:
                      storage: 1Gi
              accessModes:
                - ReadWriteOnce
  tags:
    - start
    - destroy
