---
- name: Create route
  openshift_v1_route:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: Route
          metadata:
              name: foreman
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: httpd
          spec:
              host: "{{ application_hostname }}"
              to:
                  kind: Service
                  name: httpd
              port:
                  targetPort: https
              tls:
                  termination: reencrypt
                  insecureEdgeTerminationPolicy: Allow
                  key: |-
                    {{ pulp_key }}
                  certificate: |-
                    {{ pulp_crt }}
                  ca_certificate: |-
                    {{ ca_crt }}
                  destination_c_a_certificate: |-
                    {{ ca_crt }}
  tags:
    - start
    - restart
    - destroy
