---
- name: Create HTTPS route for Foreman and Pulp
  openshift_raw:
      state: "{{ deployment_state }}"
      force: false
      definition:
          apiVersion: v1
          kind: Route
          metadata:
              name: foreman-https
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: httpd
          spec:
              host: "{{ application_hostname }}"
              to:
                  kind: Service
                  name: httpd
              port:
                  targetPort: https
              tls:
                  termination: passthrough
  tags:
    - start
    - restart
    - destroy

- name: Create HTTP route for Pub
  openshift_raw:
      state: "{{ deployment_state }}"
      force: false
      definition:
          apiVersion: v1
          kind: Route
          metadata:
              name: foreman-http-pub
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: httpd
          spec:
              host: "{{ application_hostname }}"
              path: /pub
              to:
                  kind: Service
                  name: httpd
              port:
                  targetPort: http
  tags:
    - start
    - restart
    - destroy

- name: Create HTTP route for Pulp Content
  openshift_raw:
      state: "{{ deployment_state }}"
      force: false
      definition:
          apiVersion: v1
          kind: Route
          metadata:
              name: foreman-http-pulp
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: httpd
          spec:
              host: "{{ application_hostname }}"
              path: /pulp
              to:
                  kind: Service
                  name: httpd
              port:
                  targetPort: http
  tags:
    - start
    - restart
    - destroy
