---
dependencies:
  - role: etc_hosts
  - role: foreman_server_repositories
    foreman_server_repositories_ostree: true
    foreman_server_repositories_katello: true
    foreman_server_repositories_foreman_client: true
  - role: foreman_installer_devel_scenario
  - role: foreman_installer
    katello_repositories_version: nightly
    foreman_installer_scenario: katello-devel
    foreman_installer_additional_packages:
      - foreman-installer-katello
    foreman_installer_options_internal_use_only:
      - "--disable-system-checks"
      - "--katello-devel-enable-ostree=true"
      - "--katello-devel-admin-password {{ foreman_installer_admin_password }}"
