---
dependencies:
  - role: etc_hosts
  - role: foreman_server_repositories
    foreman_server_repositories_ostree: true
    foreman_server_repositories_katello: true
    foreman_server_repositories_foreman_client: true
  - role: ruby_scl
  - role: foreman_installer_devel_scenario
  - role: foreman_installer
    katello_repositories_version: nightly
    foreman_installer_scenario: katello-devel
    foreman_installer_additional_packages:
      - foreman-installer-katello
