---
- hosts: localhost
  vars:
    project_name: 'foreman-platform'
    project_display_name: 'Foreman Platform'
    claim_name: 'local-data'
    postgresql_database: "candlepin"
    postgresql_user: "candlepin"
    postgresql_password: "candlepin"
    postgresql_volume_claim: "{{ claim_name }}"
    mongodb_volume_claim: "{{ claim_name }}"
    mongodb_database: "pulp_database"
    mongodb_user: "admin"
    mongodb_password: "admin"
    pulp_database: "{{ mongodb_database }}"
    pulp_database_user: "{{ mongodb_user }}"
    pulp_database_password: "{{ mongodb_password }}"
    pulp_content_volume_claim: "{{ claim_name }}"
    candlepin_database_user: "{{ postgresql_user }}"
    candlepin_database_password: "{{ postgresql_password }}"
    candlepin_database: "{{ postgresql_database }}"
    foreman_database: "{{ postgresql_database }}"
    foreman_database_user: "{{ postgresql_user }}"
    foreman_database_password: "{{ postgresql_password }}"
    foreman_enable_katello: true
    foreman_enable_foreman_docker: true
    foreman_enable_foreman_remote_execution: true
    foreman_enable_foreman_hooks: true
    foreman_enable_foreman_openscap: true
    foreman_enable_foreman_ansible: true
    foreman_enable_foreman_discovery: true
    puppet_volume_claim: "{{ claim_name }}"
  roles:
    - project
    - volume
    - claim
    - mongodb
    - postgresql
    - qpid
    - candlepin
    - pulp
    - foreman
    - puppet
    - foreman_proxy
