- hosts: all
  become: true
  vars:
    foreman_installer_options_internal_use_only:
      # Because we don't have a correct reverse DNS in our CI
      - "--skip-checks-i-know-better"
    foreman_repositories_version: nightly
    foreman_repositories_use_koji: true
    bats_tests:
      - "fb-test-foreman.bats"
      - "fb-finish.bats"
  roles:
    - umask
    - selinux
    - etc_hosts
    - disable_ipv6
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - disable_firewall
    - haveged
    - swapfile
    - foreman_installer
    - bats
