- hosts: all
  become: true
  vars:
    katello_repositories_version: nightly
    katello_repositories_use_koji: true
    puppet_repositories_version: 4
    foreman_installer_skip_installer: true
    foreman_installer_additional_packages:
      - katello
  roles:
    - selinux
    - etc_hosts
    - disable_ipv6
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - disable_firewall
    - haveged
    - foreman_installer
    - bats
