- hosts: all
  become: true
  roles:
    - ostree_repositories
    - puppet_repositories
    - role: foreman_installer
      foreman_installer_scenario: katello
      foreman_installer_options_internal_use_only:
        - "--disable-system-checks"
        - "--katello-enable-ostree=true"
