---
- hosts: all
  become: true
  vars:
    foreman_installer_options:
      - "--disable-system-checks"
      - "--foreman-admin-password {{ foreman_installer_admin_password }}"
      - "--enable-foreman-plugin-ansible"
      - "--enable-foreman-plugin-discovery"
      - "--enable-foreman-plugin-bootdisk"
      - "--enable-foreman-plugin-hooks"
      - "--enable-foreman-plugin-openscap"
      - "--enable-foreman-plugin-templates"
      - "--enable-foreman-plugin-remote-execution"
      - "--enable-foreman-proxy-plugin-remote-execution-ssh"
      - "--enable-foreman-proxy-plugin-discovery"
      - "--enable-foreman-proxy-plugin-ansible"
      - "--enable-foreman-proxy-plugin-openscap"
  roles:
    - role: katello
