- hosts: localhost
  tasks:
    - name: 'Bring up box for Katello'
      command: vagrant up pipeline-katello-centos7

    - name: 'Bring up box for Capsule'
      command: vagrant up pipeline-proxy-centos7

    - name: 'Refresh inventory'
      meta: refresh_inventory

- hosts: pipeline-katello-centos7
  become: yes
  vars:
    katello_version: nightly
    foreman_version: nightly
    katello_repositories_use_koji: true
  roles:
    - etc_hosts
    - foreman_repositories
    - katello_repositories
    - katello

- hosts: pipeline-proxy-centos7
  become: yes
  vars:
    foreman_proxy_content_server: pipeline-katello-centos7
    katello_version: nightly
    foreman_version: nightly
    katello_repositories_use_koji: true
  roles:
    - etc_hosts
    - foreman_repositories
    - katello_repositories
    - foreman_proxy_content

- hosts: pipeline-katello-centos7
  become: true
  roles:
    - bats
