---
- hosts: all
  become: true
  vars:
    vagrant_libvirt: true
    vagrant_version: 2.1.1
  roles:
    - role: libvirt
    - role: vagrant
    - role: epel_repositories

- hosts: all
  become: true
  tasks:
    - name: 'Install ansible'
      package:
        name: 'ansible'
        state: 'present'
    - name: 'Install git'
      package:
        name: 'git'
        state: 'present'
    - name: 'Clone Forklift'
      git:
        repo: 'http://github.com/theforeman/forklift'
        dest: './forklift'
