- hosts: all
  become: true
  vars:
    foreman_repositories_version: nightly
    katello_repositories_version: nightly
    foreman_installer_upgrade: True
    foreman_repositories_environment: staging
    katello_repositories_environment: staging
    foreman_installer_scenario: katello
  roles:
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - foreman_installer
