---
- name: 'Cleanup previous registrations'
  include_tasks: cleanup.yml
  when: katello_client_cleanup

- name: 'Install bootstrap rpm'
  yum:
    name: "http://{{ katello_client_server }}/pub/katello-ca-consumer-latest.noarch.rpm"
    state: "present"

- name: 'Register client with subscription-manager'
  redhat_subscription:
    state: "present"
    org_id: "{{ katello_client_organization }}"
    environment: "{{ katello_client_environment }}"
    username: "{{ katello_client_username }}"
    password: "{{ katello_client_password }}"

- name: 'Install katello-agent'
  yum:
    name: "katello-agent"
    state: "present"
